[service]
    host        = "localhost"
    port        = 8483
    location    = "Europe/Moscow"

    [service.timeouts]
        write   = "10s"
        read    = "10s"
        idle    = "30s"

    [service.users]
        "sber-osmp" = ""
        "sb-acq"    = ""
        "test"      = ""

[billing]
    api_url = ""
    username = ""
    password = ""
    payment_method = 2 # банковский перевод
    payment_back_method = 8 # откат платежа
    payment_report_retro = "1h" # за какой период назад от фактического времени платежа искать платёж в биллинге

[billing.tih]
    api_prefix = "tih"
    pay_id_prefix = 352120
    office = "Тихорецкий филиал"

[billing.kor]
    api_prefix = "kor"
    pay_id_prefix = 353180
    office = "Кореновский филиал"

[osmp]
    check_info = '''Оплата за Интернет'''
    time_layout = "02.01.2006_15:04:05"
    id_max_len = 18 # максимум 20 в документации, но int64 не влазит, поэтому 18
    pay_amount_min = 1
    pay_amount_max = 100000

[atol]
    api_url = ""
    request_template = '''
    {
        "uuid": "%s",
        "request": {
            "type": "sell",
            "items": [{
                "tax": {"type": "none"},
                "name": "абон. плата за Интернет [%d]",
                "type": "position",
                "price": %.2f,
                "amount": %.2f,
                "quantity": 1
            }],
            "total": %.2f,
            "operator": {"name": "%s"},
            "payments": [{"sum": %.2f, "type": "electronically"}],
            "clientInfo": {"emailOrPhone": "%s"},
            "paymentsPlace": "%s",
            "electronically": true
        }
    }
    '''
